name: Run Python
on: 
    push:
    schedule:
        - cron: 0 8 * * * # utc 格林威治時間

jobs: 
    build:
        name: run py1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: run Python
          run:
            python3 test_mail.py  # test    